### ISSUE TITLE
failure to build/run on a fresh system

### ISSUE THREAD

**Issue by hfukada** [euank/EuIrcBot#100]
```
/EuIrcBot/node_modules/irc/lib/irc.js:753
                        throw err;
                        ^

TypeError: Cannot read property 'trim' of undefined
    at Client.<anonymous> (/EuIrcBot/node_modules/irc/lib/irc.js:387:80)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at iterator (/EuIrcBot/node_modules/irc/lib/irc.js:750:26)
    at Array.forEach (native)
    at TLSSocket.<anonymous> (/EuIrcBot/node_modules/irc/lib/irc.js:745:15)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)
```

**Comment by LinuxMercedes** [comment]
This looks like an error in node-irc (which is moderately unsurprising). Are you sure you have run both `./installModules.sh` and `npm install` in the repo directory?

**Comment by euank** [comment]
To sync over the information we discovered (@hfukada, correct me if I'm getting this wrong):

This was trying to connect to an alternative IRC server implementation that might or might not be conforming to the spec.
This was entirely a node-irc library issue, nothing this codebase can fix short of changing irc library or fixing the irc library elsewhere.
I have https://github.com/euank/EuIrcBot-core which uses slate-irc instead of node-irc and @hfukada will test that at some ponit to see if it connects and, if so, we'll have a path forwards of moving to use that bot or, if that's too far out, switching this to use slate-irc in this one.

Just wanted to sync that information here as well so it's clear what's left here.

**Comment by LinuxMercedes** [comment]
Looking at this in more detail, it's almost assuredly either a non-spec-conforming IRC server or a bug in node-irc's message parsing. It doesn't look too bad to debug; if you are interested, @hfukada, I can make you a node-irc build with the right debug output.

**Comment by euank** [comment]
Since I don't think this is actually a bug in this codebase and we're short on debug information, I'm closing.

Feel free to reopen if you've got more information!
